
import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { useToast } from '@/components/ui/use-toast';
import { useData } from '@/contexts/DataContext';
import { UserPlus, Trash2, User, Briefcase, ShieldCheck } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

const ManagementTab = () => {
  const { toast } = useToast();
  const { users, addUser, removeUser } = useData();
  const [newUserName, setNewUserName] = useState('');
  const [newUserEmail, setNewUserEmail] = useState('');
  const [newUserSector, setNewUserSector] = useState('');

  const handleAddUser = async () => {
    if (!newUserName || !newUserEmail || !newUserSector) {
      toast({
        variant: "destructive",
        title: "Erro",
        description: "Por favor, preencha todos os campos do novo usuário."
      });
      return;
    }
    // Note: The 'id' will be generated by Supabase, but we can have a temporary one for the UI state if needed
    const newUser = {
      name: newUserName,
      sector: newUserSector,
      auth_email: newUserEmail,
    };
    await addUser(newUser);
    setNewUserName('');
    setNewUserEmail('');
    setNewUserSector('');
    toast({
      title: "🎉 Usuário adicionado!",
      description: `${newUserName} foi adicionado com sucesso.`
    });
  };

  const handleRemoveUser = async (userId) => {
    await removeUser(userId);
    toast({
      title: "🗑️ Usuário removido!",
      description: "O usuário foi removido com sucesso."
    });
  };

  return (
    <div className="space-y-8">
      <div>
        <h2 className="text-2xl font-bold tracking-tight text-foreground">Gerenciamento de Atendentes</h2>
        <p className="text-muted-foreground">Adicione, remova e gerencie os acessos dos atendentes.</p>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card className="glass-effect-strong text-foreground">
          <CardHeader>
            <CardTitle className="text-foreground">Adicionar Novo Usuário</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <Input 
              placeholder="Nome completo" 
              value={newUserName}
              onChange={(e) => setNewUserName(e.target.value)}
              className="bg-input text-foreground border-border placeholder:text-muted-foreground"
            />
            <Input 
              type="email"
              placeholder="Email de autenticação" 
              value={newUserEmail}
              onChange={(e) => setNewUserEmail(e.target.value)}
              className="bg-input text-foreground border-border placeholder:text-muted-foreground"
            />
            <Select onValueChange={setNewUserSector} value={newUserSector}>
              <SelectTrigger className="w-full bg-input text-foreground border-border">
                <SelectValue placeholder="Setor" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="Agendamento">Agendamento</SelectItem>
                <SelectItem value="Orçamento">Orçamento</SelectItem>
                <SelectItem value="Financeiro">Financeiro</SelectItem>
                <SelectItem value="Atendimento">Atendimento</SelectItem>
                <SelectItem value="Administrativo">Administrativo</SelectItem>
              </SelectContent>
            </Select>
            <Button onClick={handleAddUser} className="w-full" variant="glassPrimary">
              <UserPlus className="mr-2 h-4 w-4" />
              Adicionar Usuário
            </Button>
          </CardContent>
        </Card>

        <Card className="glass-effect-strong text-foreground">
          <CardHeader>
            <CardTitle className="text-foreground">Atendentes Atuais</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3 max-h-60 overflow-y-auto custom-scrollbar">
              {users && users.map(user => (
                <li key={user.id} className="flex flex-col sm:flex-row items-start sm:items-center justify-between p-3 rounded-md bg-secondary space-y-2 sm:space-y-0">
                  <div className="flex items-center space-x-3">
                    <User className="h-5 w-5 text-blue-300" />
                    <span className="font-medium">{user.name}</span>
                  </div>
                  <div className="flex items-center space-x-4">
                    <div className="flex items-center space-x-2 text-sm text-muted-foreground">
                      <Briefcase className="h-4 w-4 text-yellow-400" />
                      <span className="capitalize">{user.sector}</span>
                    </div>
                     <div className="flex items-center space-x-2 text-sm text-muted-foreground">
                       <ShieldCheck className="h-4 w-4 text-green-400" />
                       <span className="truncate max-w-[120px]">{user.auth_email}</span>
                    </div>
                    <Button variant="destructive" size="icon" className="h-8 w-8 bg-red-500/50 hover:bg-red-500/70" onClick={() => handleRemoveUser(user.id)}>
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default ManagementTab;
